image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  POETRY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/poetry"

cache:
  paths:
    - .cache/pip
    - .cache/poetry

before_script:
  - python -V
  - pip install poetry
  - poetry install

pre-commit:
  script:
    - make pre-commit

test:
  script:
    - poetry run pytest

test-live:
  script:
    - tests/live.sh

coverage:
  script:
    - poetry run coverage run --source=pricehist -m pytest
    - poetry run coverage report
  coverage: '/^TOTAL.+?(\d+\%)$/'
